LUERP/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url, static
from LUERP import views
import T1_SupplierResponse.views
from django.contrib import admin
import workflow.views
import LUERP.views
import selfhelp.urls
import basedata.urls
import purchase.urls


admin.site.site_header = 'LUTEC信息管理系统'
admin.site.site_title = '登录系统后台'
admin.site.site_footer = '宁波耀泰集团'  # 设置后台底部标题
admin.site.index_title = '管理項目'

admin.autodiscover()

api_patterns = [
    url(r'^wechat/', include("apps.wechat.views")),
    url(r'^meeting/', include("apps.meetings.views")),
]

urlpatterns = [
    url('^$', LUERP.views.home),
    #path('admin/', admin.site.urls),
    url(r"^admin/(?P<app>\w+)/(?P<model>\w+)/(?P<object_id>\d+)/change/start", workflow.views.start),
    url(r"^admin/(?P<app>\w+)/(?P<model>\w+)/(?P<object_id>\d+)/change/approve/(?P<operation>\d+)", workflow.views.approve),
    url(r"^admin/(?P<app>\w+)/(?P<model>\w+)/(?P<object_id>\d+)/change/restart/(?P<instance>\d+)", workflow.views.restart),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/basedata/', include(basedata.urls)),
    url(r'^admin/selfhelp/', include(selfhelp.urls)),
    url(r'^admin/purchase/', include(purchase.urls)),
    url(r'^tracking/', include('tracking.urls')),
    #path('T1_SupplierResponse/', admin.site.urls),
    #url(r'^index/$',views.index),
    url(r'^hello/', T1_SupplierResponse.views.index),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^sysadmin/', admin.site.urls),
    url(r'^api/', include(api_patterns)),
    # url(r'^admin/basedata/', basedata.urls),
    # url(r'^admin/selfhelp/', selfhelp.urls),
    #url(r'^T1_SupplierResponse', include('T1_SupplierResponse.urls')),
]

meeting/urls.py
# encoding: utf-8
from __future__ import absolute_import, unicode_literals

from django.conf.urls.static import static

"""meeting URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/dev/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.urls import include
from django.conf.urls import url
from django.contrib import admin

from core import utils


api_patterns = [
    url(r'^wechat/', include("apps.wechat.views")),
    url(r'^meeting/', include("apps.meetings.views")),
]

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^sysadmin/', admin.site.urls),
    url(r'^api/', include(api_patterns)),
]
if settings.DEBUG:
    urlpatterns.append(
        url(r'^api.js$', utils.generate_api_js)
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

selfhelp/urls.py
from django.conf.urls import include, url,static
import selfhelp.views

urlpatterns = [
    url(r"(?P<model>\w+)/(?P<object_id>\d+)/pay", selfhelp.views.pay_action),
]

selfhelp/models.py
# coding=utf-8
import datetime
import os
import xlrd
import decimal
from django.db import transaction
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import force_text
from django.utils.translation import ugettext_lazy as _
from common import generic
from common import const
from LUERP import settings
from basedata.models import Material,ExtraParam,Project,ExpenseAccount,Measure
from organ.models import OrgUnit


class WorkOrder(generic.BO):
    """

    """
    index_weight = 1
    code = models.CharField( "工单编号",blank=True,null=True,max_length=const.DB_CHAR_CODE_10)
    refer = models.ForeignKey("self",verbose_name="参考工单",blank=True,null=True,on_delete=models.CASCADE)
    title = models.CharField("标题",max_length=const.DB_CHAR_NAME_120)
    description = models.TextField("描述信息",blank=True,null=True)
    business_domain = models.CharField("业务域",max_length=const.DB_CHAR_CODE_4,choices=const.get_value_list('S045'),default='OT')
    classification = models.CharField("分类",max_length=const.DB_CHAR_CODE_4,choices=const.get_value_list('S044'),default='D')
    service = models.ForeignKey(Material,verbose_name="服务名称",null=True,blank=True,limit_choices_to={"is_virtual":"1"},on_delete=models.CASCADE)
    project = models.ForeignKey(Project,verbose_name="项目",null=True,blank=True,on_delete=models.CASCADE)
    status = models.CharField("状态",blank=True,null=True,default='NEW',max_length=const.DB_CHAR_CODE_6,choices=const.get_value_list('S046'))
    answer = models.TextField("答复",blank=True,null=True)
    user = models.ForeignKey(User,verbose_name="用户",blank=True,null=True,on_delete=models.CASCADE)
    attach = models.FileField("附件",blank=True,null=True,help_text=u'工单附件，不导入明细。')
    detail = models.FileField("待导入明细",blank=True,null=True,help_text=u'您可导入需求明细，模板请参考文档FD0007')

    def __str__(self):
        return u"%s-%s" % (self.code,self.title)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(WorkOrder,self).save(force_insert,force_update,using,update_fields)
        if self.service:
            material = self.service
            if self.woextravalue_set.count() < 1 and material.extraparam_set and material.extraparam_set.count() > 0:
                for param in material.extraparam_set.all():
                    extra_param = WOExtraValue.objects.create(workorder=self,param_name=param)
                    self.woextravalue_set.add(extra_param)
        item_count = WOItem.objects.filter(workorder=self).count()
        if self.detail and item_count == 0:
            path = os.path.join(settings.MEDIA_ROOT,self.detail.name)
            workbook = xlrd.open_workbook(path)
            sheet = workbook.sheet_by_index(0)
            row_count = sheet.nrows
            with transaction.atomic():
                for row_index in range(row_count):
                    row = sheet.row_values(row_index)
                    if row_index == 0:
                        doc_type = row[1]
                        if doc_type.startswith('0'):
                            break
                        else:
                            continue
                    elif row_index < 3:
                        continue
                    material = None
                    measure = None
                    try:
                        measure = Measure.objects.get(code=row[4])
                    except Exception:
                        measure = Measure.objects.create(code=row[4],name=force_text(row[5]))
                    try:
                        material = Material.objects.get(code=row[0])
                    except Exception:
                        material = Material(code=row[0],name=force_text(row[1]),spec=force_text(row[2]))
                        material.save()
                    WOItem.objects.create(workorder=self,material=material,measure=measure,amount=row[6])

    class Meta:
        verbose_name = "工单服务"
        verbose_name_plural = "工单服务"

    class Media:
        js = ('js/workorder.js',)


class WOExtraValue(models.Model):
    """

    """
    workorder = models.ForeignKey(WorkOrder,verbose_name="工单",on_delete=models.CASCADE)
    param_name = models.ForeignKey(ExtraParam,verbose_name="扩展参数",on_delete=models.CASCADE)
    param_value = models.CharField("值",blank=True,null=True,max_length=const.DB_CHAR_NAME_40)

    class Meta:
        verbose_name = "扩展信息"
        verbose_name_plural = "扩展信息"


class WOItem(models.Model):
    """

    """
    workorder = models.ForeignKey(WorkOrder,verbose_name="工单",on_delete=models.CASCADE)
    material = models.ForeignKey(Material,verbose_name= "物料",null=True,blank=True,limit_choices_to={"is_virtual":"0"},on_delete=models.CASCADE)
    amount = models.DecimalField("数量",max_digits=10,decimal_places=4,blank=True,null=True)
    measure = models.ForeignKey(Measure,verbose_name="计量单位",blank=True,null=True,on_delete=models.CASCADE)
    price = models.DecimalField( "单价",max_digits=10,decimal_places=4,blank=True,null=True)

    class Meta:
        verbose_name = "工单明细"
        verbose_name_plural = "工单明细"


class Loan(generic.BO):
    """

    """
    LOAD_STATUS = (
        ('N', "新建"),
        ('I',"IN PROGRESS"),
        ('A',"APPROVED"),
        ('P',"已支付")
    )
    index_weight = 3
    code = models.CharField("单据编号",max_length=const.DB_CHAR_CODE_10,blank=True,null=True)
    title = models.CharField("标题",max_length=const.DB_CHAR_NAME_120)
    description = models.TextField("描述信息",blank=True,null=True)
    project = models.ForeignKey(Project,verbose_name="项目",on_delete=models.CASCADE)
    user = models.ForeignKey(User,verbose_name="用户",blank=True,null=True,on_delete=models.CASCADE)
    status = models.CharField("状态",blank=True,null=True,default='N',max_length=const.DB_CHAR_CODE_2,choices=LOAD_STATUS)
    logout_time = models.DateTimeField("核销时间",blank=True,null=True)
    loan_amount = models.DecimalField("借款金额",max_digits=10,decimal_places=2,blank=True,null=True)
    logout_amount = models.DecimalField( "核销金额",max_digits=10,decimal_places=2,blank=True,null=True)
    pay_user = models.CharField("支付人",max_length=const.DB_CHAR_NAME_40,blank=True,null=True)
    pay_time = models.DateTimeField("支付时间",blank=True,null=True)
    is_clear = models.BooleanField("全部核销",default=False)

    def __str__(self):
        import decimal
        left = self.loan_amount
        left -= self.logout_amount or decimal.Decimal(0.00)
        name = '%s%s'%(self.user.last_name,self.user.first_name)
        return '%s %s %s J:%.2f Y:%.2f' % (self.code,name,self.title,self.loan_amount,left)

    def applier(self):
        return u'%s%s'%(self.user.last_name,self.user.first_name)

    applier.short_description = "申请人"

    def action_pay(self,request):
        self.pay_time = datetime.datetime.now()
        self.pay_user = request.user.username
        self.status = 'P'
        self.save()

    class Meta:
        verbose_name = "借款申请"
        verbose_name_plural ="借款申请"
        permissions = (
            ('financial_pay',_("financial pay")),
        )


class Reimbursement(generic.BO):
    """

    """
    REIM_STATUS = (
        ('N',"新建"),
        ('I',"处理中"),
        ('A',"已批准"),
        ('P',"已支付")
    )
    index_weight = 2
    code = models.CharField( "单据编号",max_length=const.DB_CHAR_CODE_10,blank=True,null=True)
    title = models.CharField("标题",max_length=const.DB_CHAR_NAME_120)
    description = models.TextField("描述信息",blank=True,null=True)
    project = models.ForeignKey(Project,verbose_name="项目",on_delete=models.CASCADE)
    wo = models.ForeignKey(WorkOrder,verbose_name="工单",null=True,blank=True,on_delete=models.CASCADE)
    user = models.ForeignKey(User,verbose_name="用户",blank=True,null=True,on_delete=models.CASCADE)
    org = models.ForeignKey(OrgUnit,verbose_name="成本中心",blank=True,null=True,on_delete=models.CASCADE)
    bank_account = models.CharField("银行账户",max_length=const.DB_CHAR_NAME_120,blank=True,null=True)
    status = models.CharField( "状态",blank=True,null=True,default='N',max_length=const.DB_CHAR_CODE_2,choices=REIM_STATUS)
    amount = models.DecimalField("金额",max_digits=10,decimal_places=2,blank=True,null=True)
    loan = models.ForeignKey(Loan,verbose_name="借款单据",blank=True,null=True,on_delete=models.CASCADE)
    loan_amount = models.DecimalField( "借款金额",max_digits=10,decimal_places=2,blank=True,null=True)
    logout_amount = models.DecimalField("核销金额",max_digits=10,decimal_places=2,blank=True,null=True)
    pay_amount = models.DecimalField("支付金额",max_digits=10,decimal_places=2,blank=True,null=True)
    pay_time = models.DateTimeField("付款日期",blank=True,null=True)
    pay_user = models.CharField("付款用户",max_length=const.DB_CHAR_NAME_40,blank=True,null=True)

    def applier(self):
        return u'%s%s'%(self.user.last_name,self.user.first_name)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        import decimal
        if self.loan:
            left = self.loan.loan_amount
            left -= self.loan.logout_amount or decimal.Decimal(0.00)
            if self.logout_amount is None or self.logout_amount == '':
                if self.amount < left:
                    self.logout_amount = self.amount
                else:
                    self.logout_amount = left
        self.pay_amount = self.amount
        if self.logout_amount:
            self.pay_amount -= self.logout_amount
        super(Reimbursement,self).save(force_insert,force_update,using,update_fields)

    def action_pay(self,request):
        if self.loan:
            if self.logout_amount is None or self.logout_amount == '':
                self.logout_amount = self.amount
            if self.logout_amount < 0:
                raise Exception(u'核销金额小于0')

            if self.loan.logout_amount is None:
                self.loan.logout_amount = self.logout_amount
            else:
                self.loan.logout_amount += self.logout_amount

selfhelp/views.py
# coding=utf-8
from django.contrib.admin import site
from django.contrib.contenttypes.models import ContentType
from django.db import connection
from django.http.response import HttpResponseRedirect
from django.utils.encoding import force_text
from django.template.response import TemplateResponse
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType


def pay_action(request, model, object_id):
    title = "确定？"
    ct = ContentType.objects.get(app_label='selfhelp',model=model)
    obj = ct.get_object_for_this_type(id=int(object_id))
    opts = obj._meta
    objects_name = force_text(opts.verbose_name)

    if model == 'reimbursement':
        loan = obj.loan
        amount = obj.logout_amount
        if loan and (amount is None or amount< 0):
            messages.error(request,u'您选择了借款单据，但是未正确填写核销金额，请在\'财务信息\'栏目中更正')
            return HttpResponseRedirect("/admin/selfhelp/%s/%s"%(model,object_id))

    if request.POST.get("post"):
        try:
            obj.action_pay(request)
            messages.success(request, "执行成功")
        except Exception:
            messages.error(request,e)

        return HttpResponseRedirect("/admin/selfhelp/%s/%s"%(model,object_id))

    context = dict(
        site.each_context(request),
        title=title,
        opts=opts,
        objects_name=objects_name,
        object=obj,
        action_name="支付"
    )
    request.current_app = site.name

    return TemplateResponse(request,'admin/invent/stockin/in_confirmation.html', context)

templates/admin1/selfhelp/workorder/change_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; {% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
&rsaquo; {% if add %}{% trans 'Add' %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endblock %}
{% endif %}

{% block content %}<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li>
        {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
        <a href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a>
    </li>
    {% if has_absolute_url %}<li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif %}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
{% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if show_workflow_line%}
<fieldset class="module aligned workflow">
    <h2>{% trans "workflow approve" %}</h2>
    <div style="padding:10px">
        {% if can_restart %}
        <a class="button" href="restart/{{workflow_instance.id}}" id="workflow_restart">{% trans "restart workflow" %}</a>
        <p style="float:right;color:#666">{% trans "your apply has been denied,you can restart a new apply" %}</p>
        {% else %}
        <label class="control"><input type="radio" name="operation" value="1" checked> {% trans "agree" %}</label>
        <label class="control"><input type="radio" name="operation" value="3"> {% trans "deny" %}</label>
        <label class="control"><input type="radio" name="operation" value="4"> {% trans "terminate" %}</label>
        <a class="button" href="approve/1" id="workflow_approve">{% trans "submit" %}</a>
        {% endif %}
    </div>
</fieldset>
{% endif %}
{% if errors %}
    <p class="errornote">
    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% block field_sets %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endblock %}

{% block after_field_sets %}{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
{% endblock %}

{% block after_related_objects %}{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

{% block admin_change_form_document_ready %}
    <script type="text/javascript">
        (function($) {
            $(document).ready(function() {
                $('.add-another').click(function(e) {
                    e.preventDefault();
                    showAddAnotherPopup(this);
                });
                $('.related-lookup').click(function(e) {
                    e.preventDefault();
                    showRelatedObjectLookupPopup(this);
                });

            {% if adminform and add %}
                $('form#{{ opts.model_name }}_form :input:visible:enabled:first').focus()
            {% endif %}
            {% if workflow_modal  %}
                {% if workflow_instance %}
                workflow_modal = "{{ workflow_modal.code }}";
                workflow_instance = "{{ workflow_instance.code }}";
                $('tr.add-row').hide();
                    {% if can_edit %}
                        $('a.deletelink').hide();
                        $("#workflow_submit").hide();
                        $("input[name='_addanother']").hide();
                        $("input[name='_continue']").hide();
                    {% else %}
                        $('input,select,textarea').attr('disabled','true');
                        $('div.submit-row').hide();
                        $('.workflow input,.workflow select').removeAttr("disabled");
                        $("#workflow_submit").hide();
                    {% endif %}
                {% endif %}
            {% else %}
                $("#workflow_submit").hide();
            {% endif %}
            {% if extra_buttons %}
                {% for button in extra_buttons %}
                    $("<a href='{{button.href}}' class='button'>{{button.title}}</a>").insertAfter("#workflow_submit");
                {% endfor %}
            {% endif %}
            {% if readonly %}
                $('input,select,textarea').attr('disabled',true);
                $('div.submit-row').hide();
                $('tr.add-row').hide();
            {% endif %}
            try{
                    $("div.inline-group table tbody tr.form-row").removeClass('has_original');
                    $("div.inline-group table tbody tr.form-row td:first-child").find('p').hide();
                }catch(e){

                }
            });
            $('#id_classification').bind('change',function(){
                var c = $("select[name='classification'] option:selected").val();
                //alert(c);
                if(c=='R' || c=='Q'){
                    $("label[for='id_service']").removeClass('required');
                    $('#woitem_set-group').hide();
                    $('#woextravalue_set-group').hide();
                    $('div.field-service').hide();
                    $('div.field-detail').hide();
                }else{
                    $('#woitem_set-group').show();
                    $('#woextravalue_set-group').show();
                    $('div.field-service').show();
                    if(c=='D'){
                        $("label[for='id_service']").removeClass('required');
                        $('div.field-detail').show();
                    }
                    if(c=='S'){
                        $('div.field-detail').hide();
                        $("label[for='id_service']").addClass('required');
                    }
                }
            });

            $('#woextravalue_set-group').hide();
        })(django.jQuery);
    </script>
{% endblock %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}